services:
  - type: web
    name: opd-portal
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: opd-db
          property: connectionString

databases:
  - name: opd-db
    plan: free

